package com.mochame.sync.spi.network

import com.mochame.sync.common.readLongAt
import com.mochame.sync.common.writeLongAt

/**
 * Service Provider Interface (SPI) defining client-side transport abstraction for sync communication.
 *
 * Facilitates bidirectional frame delivery, lifecycle hooks, and flow control.
 */
interface SyncTransport {
    /**
     * Whether the underlying socket or connection channel is active and capable of sending frames.
     */
    val isConnected: Boolean
    suspend fun connect(host: String, port: Int, groupId: String)

    /**
     * Dispatches an upstream batch to the sync relay.
     *
     * @param batchId Monotonically increasing batch identifier generated by the client, necessary on Ack.
     * @param payload Serialized data.
     * @return [SendResult] describing whether the frame was dispatched, failed, or blocked by connection loss.
     */
    suspend fun send(batchId: Long, payload: ByteArray): SendResult

    fun pause()
    fun resume()

    fun registerInboundAckHandler(onAck: suspend (Long, Long) -> Unit)
    fun registerInboundDeltaHandler(onReceived: suspend (Long, ByteArray) -> Unit)
    fun setOnConnectedListener(onConnected: suspend () -> Unit)
    fun setOnDisconnectedListener(onDisconnected: suspend () -> Unit)
}

sealed interface SendResult {
    data object Success : SendResult
    data object NoConnection : SendResult
    data class Failure(val cause: Throwable) : SendResult
}

/**
 * Parsed representations of possible frame types.
 */
sealed interface WireFrame {
    /** Indicates historical catch-up streaming is finished. */
    data object BackfillComplete : WireFrame
    /** Server acknowledgment confirming a committed batch. */
    data class Ack(val batchId: Long, val watermark: Long) : WireFrame
    /** Broadcast delta from a remote peer. */
    data class Delta(val watermark: Long, val payload: ByteArray) : WireFrame
    /** Client intent received by the server. */
    data class ClientSubmit(val batchId: Long, val payload: ByteArray) : WireFrame
}

/**
 * [WireFrame] serialization and deserialization protocol.
 *
 * Wire format layouts (big-endian):
 * - **BackfillComplete:** `[0x01]` (1 byte)
 * - **Ack:** `[0x02][batchId: 8B][watermark: 8B]` (17 bytes)
 * - **Batch (ClientSubmit):** `[0x04][batchId: 8B][payload: NB]` (9+ bytes)
 * - **Delta:** `[0x03][watermark: 8B][payload: NB]` (9+ bytes)
 */
object WireFrameFactory {
    private const val OP_BACKFILL_COMPLETE: Byte = 0x01
    private const val OP_ACK: Byte = 0x02
    private const val OP_DELTA: Byte = 0x03
    private const val OP_CLIENT_SUBMIT: Byte = 0x04

    /**
     * Encodes a 1-byte delimiter frame signaling the end of historical backfill.
     * This implies the client is now receiving live peer broadcasts.
     */
    fun backfillComplete(): ByteArray = byteArrayOf(OP_BACKFILL_COMPLETE)

    /** Encodes an acknowledgment frame assigning a persistent watermark to a submitted batch ID. */
    fun ack(batchId: Long, watermark: Long): ByteArray {
        val out = ByteArray(17)
        out[0] = OP_ACK
        out.writeLongAt(1, batchId)
        out.writeLongAt(9, watermark)
        return out
    }

    /** Encodes an upstream client mutation batch frame. */
    fun batch(batchId: Long, payload: ByteArray): ByteArray {
        val out = ByteArray(9 + payload.size)
        out[0] = OP_CLIENT_SUBMIT
        out.writeLongAt(1, batchId)
        payload.copyInto(out, destinationOffset = 9)
        return out
    }

    /** Encodes a downstream delta broadcast frame. */
    fun delta(watermark: Long, payload: ByteArray): ByteArray {
        val out = ByteArray(9 + payload.size)
        out[0] = OP_DELTA
        out.writeLongAt(1, watermark)
        payload.copyInto(out, destinationOffset = 9)
        return out
    }

    /**
     * Decodes a raw binary packet into its typed [WireFrame] representation.
     *
     * @throws IllegalArgumentException If the byte array is empty or does not meet the expected opcode size.
     * @throws IllegalStateException If the first byte does not match a known opcode.
     */
    fun unwrap(bytes: ByteArray): WireFrame {
        require(bytes.isNotEmpty()) { "Malformed frame: Empty payload" }

        return when (bytes[0]) {
            OP_BACKFILL_COMPLETE -> WireFrame.BackfillComplete

            OP_ACK -> {
                require(bytes.size == 17) { "Malformed Ack frame: Expected 17 bytes, got ${bytes.size}" }
                val batchId = bytes.readLongAt(1)
                val watermark = bytes.readLongAt(9)
                WireFrame.Ack(batchId, watermark)
            }

            OP_DELTA -> {
                require(bytes.size >= 9) { "Malformed Delta frame: Expected >= 9 bytes, got ${bytes.size}" }
                val watermark = bytes.readLongAt(1)
                val payload = bytes.copyOfRange(9, bytes.size)
                WireFrame.Delta(watermark, payload)
            }

            OP_CLIENT_SUBMIT -> {
                require(bytes.size >= 9) { "Malformed ClientSubmit frame: Expected >= 9 bytes, got ${bytes.size}" }
                val batchId = bytes.readLongAt(1)
                val payload = bytes.copyOfRange(9, bytes.size)
                WireFrame.ClientSubmit(batchId, payload)
            }

            else -> error("Unknown wire frame opcode: 0x${bytes[0].toString(16)}")
        }
    }
}